spring:
  kafka:
    consumer:
      bootstrap-servers: 40.69.78.245:19092
      group_id: cashback
      topic: transactions
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        request.timeout.ms: 20000
#        spring.json.type.mapping: ru.tinkoff.bpm.kotlincoursepaymentprocessing.kafka.TransactionInfo:ru.tinkoff.fintech.model.Transaction
#        spring.json.value.default.type: ru.tinkoff.fintech.model.Transaction

  datasource:
    url: ****
    username: ****.postgres.database.azure.com
    password: ****
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  transactionProcessor:
    services:
      uri:
        card: http://****/card-service/api/v1/card
        client: http://****/client-service/api/v1/client
        loyalty: http://****/loyalty-service/api/v1/program
        notification: http://****/notification-service/api/v2/client
      sign: chebykin

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG
