spring:
  kafka:
    consumer:
      bootstrap-servers: 40.69.78.245:19092
      group_id: cashback
      topic: transactions
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        request.timeout.ms: 20000
#        spring.json.type.mapping: ru.tinkoff.bpm.kotlincoursepaymentprocessing.kafka.TransactionInfo:ru.tinkoff.fintech.model.Transaction
#        spring.json.value.default.type: ru.tinkoff.fintech.model.Transaction

  datasource:
    url: jdbc:postgresql://tinkoff-kotlin-psql-1.postgres.database.azure.com:5432/fintech?currentSchema=cashback
    username: kotlin_master@tinkoff-kotlin-psql-1.postgres.database.azure.com
    password: koklin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  transactionProcessor:
    services:
      uri:
        card: http://13.79.17.165/card-service/api/v1/card
        client: http://13.79.17.165/client-service/api/v1/client
        loyalty: http://13.79.17.165/loyalty-service/api/v1/program
        notification: http://13.79.17.165/notification-service/api/v2/client
      sign: chebykin

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG
